name: workflow call example
on: 
  workflow_dispatch:
  push:

jobs:
  run-2-workflow-call:
    runs-on: ubuntu-latest
  

    steps: 
      - name: app_name
        run: |
          echo "The app name is "


  applications_testing:
    runs-on: ubuntu-latest
    
    needs: 
     - run-2-workflow-cal

    steps: 
      - name: applications testing with trivy
        run: |
          echo "Running applications Unite test "
          echo "Test has passed"

  Deploy_the_app:
    needs: 
     - applications_testing

    uses: ./github/workflows/centrall-deploy.yaml   
    with:
      app_name: Payment-yoag
      security_scans: true
      replicas_count: 3
