name: dispatch-test

on:
  workflow_dispatch:

jobs:
  validations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run app
        run: |
          python3 test/app.py
