name: dispatch-test

on:
  workflow_dispatch: 

jobs:
  validations:
    runs-on: ubuntu-latest      
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: run validatinons
        run: python3 /test/app.py
 